### ISSUE TITLE
Postcss rem() doesn't work with Vite 5

### ISSUE THREAD

**Issue by noramichalski** [mantinedev/postcss-preset-mantine#9]
Followed documentations https://mantine.dev/styles/postcss-preset/ and https://mantine.dev/guides/vite/ and I can't implement the navbar component (NavbarNested) based on the examples in https://ui.mantine.dev/category/navbars/ because the rem() functions keep breaking.

![screenshot 2024-01-08 at 6 02 01 PM](https://github.com/mantinedev/postcss-preset-mantine/assets/20412903/903083a6-aa6f-4ae1-9315-a1913c80c973)

vite: 5.0.11
postcss.config.cjs:
```
module.exports = {
  plugins: {
    "postcss-preset-mantine": {},
    "postcss-simple-vars": {
      variables: {
        "mantine-breakpoint-xs": "36em",
        "mantine-breakpoint-sm": "48em",
        "mantine-breakpoint-md": "62em",
        "mantine-breakpoint-lg": "75em",
        "mantine-breakpoint-xl": "88em",
      },
    },
  },
};
```
In App.tsx:
```
import { MantineProvider } from "@mantine/core";
import "@mantine/core/styles.css";
(...)
<MantineProvider>
    <App />
</MantineProvider>
```

**Comment by rtivital** [comment]
You can find a working template with Vite 5 here – https://github.com/mantinedev/vite-template

**Comment by paulcarroll** [comment]
FWIW I've just upgraded and run into this issue. I have always had the postcss mantine plugin configured, but now it's complaining my existing e.g. `rem(20px)` are missing a parameter (due to the new [css rem function](https://developer.mozilla.org/en-US/docs/Web/CSS/rem))

I've gone over the provided Vite 5 template repo, but something has changed with the Vite 5 and Mantine upgraded pipeline.

Will report back when I find the solution to my problem here
